reference_jdk: &reference_jdk
                 'JDK="adopt@1.11.28-0"'
reference_os: &reference_os
                'linux'
official_repo: &official_repo
                 'lippo997/Protelis-Demo'
language: bash
git:
  depth: false
os:
  - osx
  - windows
  - *reference_os
dist: xenial
stages:
  - check
  - test
env:
  global:
    - TERM=dumb
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    - PUBLISH="false"
    - OFFICIAL_REPO_SLUG="lippo997/Protelis-Demo"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.11.0-3"
    - JDK="adopt@1.12.33-0"
    - JDK="adopt-openj9@1.12.33-0"
matrix:
  exclude:
    - os: *reference_os
      env: *reference_jdk
jobs:
  include:
    - stage: check
      name: "Deep check on reference OS and JDK"
      os: *reference_os
      env:
        - *reference_jdk
      script:
        - cd "$TRAVIS_BUILD_DIR"
        - ./gradlew clean check --parallel
before_install:
  - curl "${GRAVIS}.disable-windows-defender.sh" --output .disable-windows-defender.sh
  - source .disable-windows-defender.sh
  - curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  - source .install-jdk-travis.sh
script:
  - cd "$TRAVIS_BUILD_DIR"/alchemist
  - ./gradlew clean test --parallel
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - bash .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/