[protelis]
iterations = 4
protelisModuleName = "hello"

[[protelis.nodes]]
    hostandport = { host = "localhost", port = 10000 }
    id = 0
    neighbors = [{ host = "localhost", port = 10004 }, { host = "localhost", port = 10001 }]
    leader = true
[[protelis.nodes]]
    hostandport = { host = "localhost", port = 10001 }
    id = 1
    neighbors = [{ host = "localhost", port = 10000 }, { host = "localhost", port = 10002 }]
[[protelis.nodes]]
    hostandport = { host = "localhost", port = 10002 }
    id = 2
    neighbors = [{ host = "localhost", port = 10001 }, { host = "localhost", port = 10003 }]
[[protelis.nodes]]
    hostandport = { host = "localhost", port = 10003 }
    id = 3
    neighbors = [{ host = "localhost", port = 10002 }, { host = "localhost", port = 10004 }]
[[protelis.nodes]]
    hostandport = { host = "localhost", port = 10004 }
    id = 4
    neighbors = [{ host = "localhost", port = 10003 }, { host = "localhost", port = 10000 }]

