[versions]
kotest = "6.1.3"
kotlin = "2.3.10"
mockito = "5.21.0"

[libraries]
jgrapht-core = "org.jgrapht:jgrapht-core:1.5.2"
junit-bom = "org.junit:junit-bom:6.0.3"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
konf = "com.uchuhimo:konf:1.1.2"
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockk = "io.mockk:mockk:1.14.9"
moquette-broker = "de.fraunhofer.iosb.io.moquette:moquette-broker:0.18.3"
paho = "org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5"
protelis = "org.protelis:protelis:18.5.3"
spotbugs-annotations = "com.github.spotbugs:spotbugs-annotations:4.9.8"

[bundles]
junit-runtime = [ "junit-platform-launcher", "junit-jupiter-engine" ]
mockito = [ "mockito-core", "mockito-junit-jupiter" ]

[plugins]
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:7.0.12"
java-qa = "org.danilopianini.gradle-java-qa:1.165.0"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:1.0.1"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:4.3.2"
shadowJar = "com.gradleup.shadow:9.3.1"
